# Generated by Django 3.1.3 on 2022-07-01 03:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(default='', max_length=50, unique=True)),
                ('item_description', models.CharField(max_length=75, null=True)),
                ('MRP', models.FloatField(default=0)),
                ('BP', models.FloatField(default=0)),
                ('MOQ', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('billing_address', models.CharField(default=None, max_length=150, null=True)),
                ('pincode', models.CharField(default=None, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.CharField(default='CSPL/', max_length=20)),
                ('enq_ref', models.CharField(default='', max_length=30)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.FloatField(default=0.0)),
                ('totalnos', models.IntegerField(default=0.0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.party')),
            ],
        ),
        migrations.CreateModel(
            name='TandC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.CharField(default='Prices are net', max_length=50)),
                ('taxes', models.CharField(default='18% GST extra as applicable', max_length=50)),
                ('delivery', models.CharField(default='Ex stock at vasai', max_length=20)),
                ('payment', models.CharField(default='50% advance payment along with po & balance against proforma invoice', max_length=80)),
                ('validity', models.CharField(default='30 days from today.', max_length=30)),
                ('freight', models.CharField(default='On to pay basis', max_length=20)),
                ('comments', models.TextField(default='We are looking forward to your response, regarding the above.\nIn case on any query please contact us immediately\nFrom Citroenswitchgears Pvt Ltd\nRegards\nJatin')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(default='', max_length=50)),
                ('qno', models.CharField(default='CSPL/', max_length=20)),
                ('refno', models.CharField(default='', max_length=20)),
                ('item_description', models.CharField(max_length=75, null=True)),
                ('price_quoted', models.FloatField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0.0, null=True)),
                ('margin', models.FloatField(default=0.0, null=True)),
                ('sub_total', models.FloatField(default=0.0)),
                ('is_converted', models.BooleanField(default=False)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.quotation')),
            ],
        ),
    ]
