# Generated by Django 3.1.3 on 2022-04-18 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(default='', max_length=50)),
                ('item_description', models.CharField(max_length=75, null=True)),
                ('MRP', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('billing_address', models.CharField(default=None, max_length=150, null=True)),
                ('pincode', models.CharField(default=None, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.FloatField(default=0.0)),
                ('totalnos', models.IntegerField(default=0.0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.party')),
            ],
        ),
        migrations.CreateModel(
            name='TandC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.CharField(default='Prices are net', max_length=20)),
                ('taxes', models.CharField(default='18% GST extra as applicable', max_length=20)),
                ('delivery', models.CharField(default='Ex stock at vasai', max_length=20)),
                ('payment', models.CharField(default='50% advance payment along with po & balance against proforma invoice', max_length=20)),
                ('validity', models.CharField(default='30 days from today.', max_length=20)),
                ('freight', models.CharField(default='On to pay basis', max_length=20)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(default='', max_length=50)),
                ('price_quoted', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0.0, null=True)),
                ('sub_total', models.FloatField(default=0.0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quotation')),
            ],
        ),
    ]
