# Generated by Django 3.1.3 on 2022-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandc',
            name='payment',
            field=models.CharField(default='50% advance payment along with po & balance against proforma invoice', max_length=80),
        ),
        migrations.AlterField(
            model_name='tandc',
            name='prices',
            field=models.CharField(default='Prices are net', max_length=50),
        ),
        migrations.AlterField(
            model_name='tandc',
            name='taxes',
            field=models.CharField(default='18% GST extra as applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='tandc',
            name='validity',
            field=models.CharField(default='30 days from today.', max_length=30),
        ),
    ]
