# Generated by Django 3.1.3 on 2022-08-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quotationitems_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitems',
            name='brand',
            field=models.CharField(choices=[('abb', 'ABB'), ('legrand', 'LEGRAND'), ('phoenix mecano', 'PHEONIX MECANO'), ('eaton', 'EATON'), ('Bussmann', 'Bussmann')], default='Bussmann', max_length=40, null=True),
        ),
    ]
