# Generated by Django 3.1.3 on 2022-04-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220418_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='tandc',
            name='comments',
            field=models.TextField(default='We are looking forward to your response, regarding the above.\nIn case on any query please contact us immediately\nfor Citroenswitchgears Pvt Ltd\nRegards\nJatin'),
        ),
    ]
