# Generated by Django 3.1.3 on 2022-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tandc_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitems',
            name='qno',
            field=models.CharField(default='CSPL/', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationitems',
            name='refno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
