# Generated by Django 3.1.3 on 2022-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220418_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
