# Generated by Django 3.1.3 on 2022-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220419_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qno',
            field=models.CharField(default='CSPL/', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='refno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
