# Generated by Django 3.1.3 on 2022-04-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220421_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qno',
        ),
        migrations.RemoveField(
            model_name='item',
            name='refno',
        ),
        migrations.AddField(
            model_name='quotation',
            name='qno',
            field=models.CharField(default='CSPL/', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='refno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
