# Generated by Django 3.1.3 on 2022-04-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220421_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='refno',
            new_name='enq_ref',
        ),
    ]
