# Generated by Django 3.1.3 on 2022-04-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220422_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='enq_ref',
            field=models.CharField(default='', max_length=30),
        ),
    ]
