# Generated by Django 3.1.3 on 2022-09-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220926_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitems',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quotation'),
        ),
    ]
