# Generated by Django 3.1.3 on 2022-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220422_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitems',
            name='price_quoted',
            field=models.FloatField(default=0),
        ),
    ]
