# Generated by Django 3.1.3 on 2022-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220422_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitems',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
