# Generated by Django 3.1.3 on 2022-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220423_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandc',
            name='comments',
            field=models.TextField(default='We are looking forward to your response, regarding the above.\nIn case on any query please contact us immediately\nFrom Citroenswitchgears Pvt Ltd\nRegards\nJatin'),
        ),
    ]
