# Generated by Django 3.1.3 on 2022-04-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220424_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='BP',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='MOQ',
            field=models.IntegerField(default=0),
        ),
    ]
