# Generated by Django 3.1.3 on 2022-04-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220425_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandc',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.quotation'),
        ),
    ]
