# Generated by Django 3.1.3 on 2022-04-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_quotationitems_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandc',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quotation'),
        ),
    ]
