# Generated by Django 3.1.3 on 2022-04-27 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220427_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitems',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.quotation'),
        ),
    ]
